name: eventful-transformer
channels:
  - defaults
dependencies:
  - ffmpeg=4.2
  - matplotlib=3.7
  - numpy=1.23
  - nvidia::cuda=11.8
  - nvidia::cuda-nvcc=11.8  # For building Detectron2
  - pandas=1.5
  - pip=23.0
  - python=3.10
  - pytorch::pytorch-cuda=11.8
  - pytorch::pytorch=2.0
  - pytorch::torchvision=0.15
  - requests=2.28
  - scipy=1.10
  - tensorboard=2.11
  - torchmetrics=0.11
  - tqdm=4.65.*
  - pip:
      - av==10.0.*
      - omegaconf==2.3.*
      - opencv-python==4.7.*  # Required for Detectron visualizer

      # This builds Detectron2 from source (requires gcc >= 5.4).
      # The specified commit hash corresponds to Detectron2 0.6.
      - git+https://github.com/facebookresearch/detectron2.git@88217cad6d741ea1510d13e54089739f5a0f4d7d
